spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/test
    username: postgres
    password: terrrr
    driver: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: none # создает таблицы если не существует, дополняет существующие таблицы колонками
      #ddl-auto: create - удаляет перед созданием существующие таблицы, создает новые
      #ddl-auto: create-drop - тоже что и create + при окончании работы приложения удаляет существующие таблицы
      #ddl-auto: none - не будет создавать, удалять, изменять сущности(таблицы, сиквенсы, констрейнты) в бд
    show-sql: true #Отображение sql запросов, который генерирует Hibernate или JPA
    properties:
      hibernate:
        format_sql: true #Форматирование запросов (красивое отображение)